- name: Initialize Kubernetes Master Node
  hosts: controlplane_server
  become: true
  tasks:
    - name: Initialize Kubernetes Cluster
      command: kubeadm init --apiserver-advertise-address={{ ansible_default_ipv4.address }} --pod-network-cidr={{ pod_network_cidr }} --upload-certs
      args:
        creates: /etc/kubernetes/admin.conf  # Prevents re-running if already initialized
      register: kubeadm_init
      changed_when: "'already initialized' not in kubeadm_init.stdout"

    - name: Create .kube directory for user
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: "0755"

    - name: Copy kubeconfig to user's kube directory
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
        group: ubuntu
        mode: "0644"

    - name: Apply Flannel CNI
      become_user: ubuntu
      command: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
      register: cni_apply
      changed_when: "'created' in cni_apply.stdout"

    - name: Retrieve Kubernetes Join Command
      block:
        - name: Get join command
          command: kubeadm token create --print-join-command
          register: join_command
          changed_when: false

        - name: Save join command to a file
          copy:
            content: "{{ join_command.stdout }}"
            dest: "/tmp/kube_join_command.sh"
            mode: "0644"

        - name: Display join command
          debug:
            msg: "{{ join_command.stdout }}"

        - name: Fetch join command from master to local machine
          fetch:
            src: "/tmp/kube_join_command.sh"  # From master
            dest: "./kube_join_command.sh"    # To local Ansible machine
            flat: yes
