---
- name: Update system packages
  yum:
    name: '*'
    state: latest

- name: Download Jenkins repository
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins repository key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

- name: Upgrade system packages
  yum:
    name: '*'
    state: latest

- name: Install Java 17 Amazon Corretto
  yum:
    name: java-17-amazon-corretto
    state: present

- name: Install Jenkins
  yum:
    name: jenkins
    state: present

- name: Create some directories
  file:
    path: "{{ jenkins_init_groovy_dir }}"
    state: directory
    owner: "{{ jenkins_uid }}"
    group: "{{ jenkins_uid }}"
    mode: "755"

- name: Place basic security script in groovy directory
  template:
    src: "templates/basic-security.groovy.j2"
    dest: "/var/lib/jenkins/init.groovy.d/basic-security.groovy"
    mode: "644"
    owner: "{{ jenkins_uid }}"
    group: "{{ jenkins_uid }}"

- name: Enable Jenkins service
  systemd:
    name: jenkins
    enabled: yes
    state: started