---
- name: Update system packages
  yum:
    name: '*'
    state: latest

- name: Download Jenkins repository
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins repository key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

- name: Upgrade system packages
  yum:
    name: '*'
    state: latest

- name: Install Java 17 Amazon Corretto
  yum:
    name: java-17-amazon-corretto
    state: present

- name: Install Jenkins
  yum:
    name: jenkins
    state: present

- name: Enable Jenkins service
  systemd:
    name: jenkins
    enabled: yes
    state: started